export default {
  TEST_TREE: "Arvore de Testes",
  USERNAME: "Usuário",
  PASSWORD: "Senha",
  CONFIRM_PASSWORD: "Confirme a senha",
  LOGIN: "Entrar",
  PROJECT: "Projeto",
  VERSION: "Versão",
  TEAM: "Equipe",
  HELP: "Ajuda",
  EXECUTE: "Executar",
  NOTES: "Notas",
  RESOLUTION: "Resolução",
  NAME: "Nome",
  ROLE: "Papel",
  PASSED: "Passou",
  FAILED: "Falhou",
  EMAIL: "E-mail",
  EDIT: "Editar",
  CREATE: "Criar",
  ADD_STEP: "Adicionar passo",
  SAVE: "Salvar",
  SAVE_SCRIPT: "Salvar roteiro",
  ACTIONS: "Ações",
  CONTENT: "Conteúdo",
  ADD_USER: "Adicionar usuário",
  DESCRIPTION: "Descrição",
  HELLO_WORLD: "HELLO WORLD",
  SEE_ALL: "Ver tudo",
  FEATURE: "Funcionalidade",
  FEATURES: "Funcionalidades",
  CREATE_FEATURE: "Criar funcionalidade",
  TEST_CASE: "Caso de teste",
  TEST_CASES: "Casos de teste",
  GIVEN: "Dado",
  WHEN: "Quando",
  THEN: "Então",
  AND: "E",
  BUT: "Mas",
  LOGOUT: "Deslogar",
  TEST_EXECUTION: "Execução de teste",
  TEST_EXECUTIONS: "Execuções de teste",
  TEST_SCRIPT: "Roteiro de teste",
  TEST_SCRIPTS: "Roteiros de teste",
  CREATE_TEST_CASE: "Criar caso de teste",
  CREATE_TEST_EXECUTION: "Criar execução de teste",
  CREATE_TEST_SCRIPT: "Criar roteiro de teste",
  EXECUTION_DATE: "Data de Execução",
  EXECUTION_BY: "Executado por",
  RESULT: "Resultado",
  VALIDATION_STRING_REQUIRED: "Campo Obrigatório",
  VALIDATION_STRING_EMAIL: "Formato incorreto de e-mail",
  HELP_CONTENT:
    "A Árvore de Testes se apresenta como uma ferramenta interessante e eficaz ao ser adicionada ao fluxo de trabalho do controle de qualidade de uma empresa de desenvolvimento de software. Desenvolvida com tecnologias atuais, no entanto consolidadas como React, NodeJS e MongoDB, otimizada para instalação em nuvem e com foco em instalações mais baratas ou até de graça, torna-se uma ferramenta com um baixíssimo impacto financeiro para seu uso. Com extrema capacidade e facilidade para melhorias na implementação e customizações, por ser de código-aberto pode ser incrementada de uma forma que toda a comunidade de usuários beneficiará das melhorias.",
};
